CREATE TABLE IF NOT EXISTS SIGNAL
(
    ID           INTEGER PRIMARY KEY REFERENCES ELEMENT (ID),
    DISPLAY_NAME TEXT    NOT NULL UNIQUE,
    INDICATION   INTEGER NOT NULL DEFAULT 0 CHECK (INDICATION IN (0, 1)),
    POINTS_TO    INTEGER NOT NULL REFERENCES ELEMENT (ID)
);

CREATE TABLE IF NOT EXISTS SWITCH
(
    ID            INTEGER PRIMARY KEY REFERENCES ELEMENT (ID),
    DISPLAY_NAME  TEXT    NOT NULL UNIQUE,
    POSITION      INTEGER NOT NULL CHECK (POSITION IN (0, 1)),
    BASE_POSITION INTEGER NOT NULL CHECK (BASE_POSITION IN (0, 1)),
    LEFT_ID       INTEGER NOT NULL REFERENCES ELEMENT (ID),
    RIGHT_ID      INTEGER NOT NULL REFERENCES ELEMENT (ID)
);

CREATE TABLE IF NOT EXISTS OPEN_TRACK
(
    ID           INTEGER PRIMARY KEY REFERENCES ELEMENT (ID),
    DISPLAY_NAME TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ELEMENT
(
    ID           INTEGER PRIMARY KEY,
    LOCKED       INTEGER NOT NULL CHECK (LOCKED IN (0, 1)),
    ELEMENT_TYPE TEXT    NOT NULL CHECK (ELEMENT_TYPE IN ('SIGNAL', 'SWITCH', 'OPEN_TRACK'))
);

CREATE TABLE IF NOT EXISTS GRAPH
(
    VERTEX    INTEGER NOT NULL REFERENCES ELEMENT (ID),
    NEIGHBOUR INTEGER NOT NULL REFERENCES ELEMENT (ID),

    PRIMARY KEY (VERTEX, NEIGHBOUR)
)
