CREATE TABLE IF NOT EXISTS SIGNAL
(
    ID             INTEGER PRIMARY KEY REFERENCES ELEMENT (ID),
    DISPLAY_NAME   TEXT    NOT NULL UNIQUE,
    POINTS_TO_TYPE TEXT    NOT NULL CHECK (POINTS_TO_TYPE IN ('signal', 'switch', 'open-track')),
    POINTS_TO      INTEGER NOT NULL REFERENCES ELEMENT (ID)
);

CREATE TABLE IF NOT EXISTS SWITCH
(
    ID            INTEGER PRIMARY KEY REFERENCES ELEMENT (ID),
    DISPLAY_NAME  TEXT    NOT NULL UNIQUE,
    BASE_POSITION INTEGER NOT NULL CHECK (BASE_POSITION IN (0, 1)),
    LEFT_ID       INTEGER NOT NULL REFERENCES ELEMENT (ID),
    RIGHT_ID      INTEGER NOT NULL REFERENCES ELEMENT (ID)
);

CREATE TABLE IF NOT EXISTS OPEN_TRACK
(
    ID           INTEGER PRIMARY KEY REFERENCES ELEMENT (ID),
    DISPLAY_NAME TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ELEMENT
(
    ID           INTEGER PRIMARY KEY,
    ELEMENT_TYPE TEXT NOT NULL CHECK (ELEMENT_TYPE IN ('signal', 'switch', 'open-track'))
);

CREATE TABLE IF NOT EXISTS GRAPH
(
    VERTEX INTEGER NOT NULL REFERENCES ELEMENT (ID),
    EDGE   INTEGER NOT NULL REFERENCES ELEMENT (ID),

    PRIMARY KEY (VERTEX, EDGE)
);
