name: Build C project

on: [push]

env:
  PICO_SDK_PATH: ../../lib/pico-sdk # Yeah, this variable is used within another directory

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone # Checkout root
        uses: actions/checkout@v3

      - name: Clone submodules # Checkout rest
        shell: bash
        run: |
          # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
          # git config --global url."https://github.com/".insteadOf "git@github.com:"
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt dist-upgrade
          sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib

      - name: Build modules
        run: |
          make -C rail

      - name: Build embedded
        run: |
          cmake -B rail/embedded/build -S rail/embedded
          make -C rail/embedded/build
