name: Build LateX project (Branch)

on: [ push ]

env:
    TEX_SOURCE_DIRECTORY: Thesis
    TEX_SOURCE: Thesis
    TEX_PDF_NAME: Thesis

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        container: texlive/texlive

        steps:
            -   name: Clone
                uses: actions/checkout@v2

            -   name: Get short commit SHA
                uses: benjlevesque/short-sha@v1.2
                id: short-sha

                with:
                    length: 8

            -   name: Compile to PDF
                run: sh .vscode/build.sh

                env:
                    TEX_PDF_NAME: ${{ env.TEX_PDF_NAME }}-${{ env.SHA }}
            
            -   name: Upload PDF
                uses: actions/upload-artifact@v3

                with:
                    name: ${{ env.TEX_PDF_NAME }}.pdf
                    path: ${{ env.TEX_SOURCE_DIRECTORY }}/build/${{ env.TEX_PDF_NAME }}.pdf

                env:
                    TEX_PDF_NAME: ${{ env.TEX_PDF_NAME }}-${{ env.SHA }}
